document.getElementById("footer").innerHTML="<div class="
+"footer"
+"><a href="
+"http://hifs.tk"
+">hifs.tk"
+" "
+"</a><a href="
+"mailto:i@hifs.tk"
+">联系我</a> <a href="
+"http://hifs.tk/About.htm"
+">关于我</a><p style='color: darkslategray; font-family: "
+"clicker script"
+","
+"segoe script"
+","
+"Comic Sans MS"
+"; font-size: 28px; margin-top: 1px; text-shadow: none;'>"
+"life,love,linux"
+"</p></div>";
